// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xrocter.Models;

#nullable disable

namespace cis_476_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231118041156_DatabasePopulation_Questions_Added")]
    partial class DatabasePopulation_Questions_Added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("cis_476_project.Models.CreditCard", b =>
                {
                    b.Property<Guid>("CardNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CVV")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IssueDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CardNumber");

                    b.HasIndex("VaultId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("cis_476_project.Models.Login", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginId");

                    b.HasIndex("VaultId");

                    b.ToTable("Login_Credentails");

                    b.HasData(
                        new
                        {
                            LoginId = new Guid("80c5cbac-77cb-43cb-9742-323e23269aee"),
                            Password = "Karya99DA",
                            URL = "www.denizkaryaacikbas.com",
                            Username = "denizkarya1999",
                            VaultId = new Guid("c5791f59-1979-4f92-89d4-0bcb203fd9da")
                        });
                });

            modelBuilder.Entity("cis_476_project.Models.SecurityNote", b =>
                {
                    b.Property<Guid>("SecurityNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SecurityNoteId");

                    b.HasIndex("VaultId");

                    b.ToTable("SecurityNotes");
                });

            modelBuilder.Entity("cis_476_project.Models.SecurityQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cd05b5f-e408-4e86-a38c-9a107f749ba5"),
                            Answer = "Zuhtupasha",
                            Question = "What was the first school you went to?",
                            UserAccountId = new Guid("07651a69-b24a-416e-abdf-d944a18c72df")
                        },
                        new
                        {
                            Id = new Guid("bb69d521-54ad-43c5-801b-82ce093485ba"),
                            Answer = "United Kingdom",
                            Question = "What was the first country you have ever visited?",
                            UserAccountId = new Guid("07651a69-b24a-416e-abdf-d944a18c72df")
                        },
                        new
                        {
                            Id = new Guid("fa3c4f57-1758-4c81-8e62-989889522402"),
                            Answer = "Tahrish",
                            Question = "What was the name of your first pet?",
                            UserAccountId = new Guid("07651a69-b24a-416e-abdf-d944a18c72df")
                        });
                });

            modelBuilder.Entity("cis_476_project.Models.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VaultId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("VaultId")
                        .IsUnique();

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("07651a69-b24a-416e-abdf-d944a18c72df"),
                            Email = "dacikbas@umich.edu",
                            Name = "Deniz",
                            Password = "Karya99DA",
                            Surname = "Acikbas",
                            VaultId = new Guid("c5791f59-1979-4f92-89d4-0bcb203fd9da")
                        });
                });

            modelBuilder.Entity("cis_476_project.Models.Vault", b =>
                {
                    b.Property<Guid>("VaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Lock")
                        .HasColumnType("bit");

                    b.Property<bool?>("Mask")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VaultId");

                    b.ToTable("Vaults");

                    b.HasData(
                        new
                        {
                            VaultId = new Guid("c5791f59-1979-4f92-89d4-0bcb203fd9da"),
                            Lock = false,
                            Mask = false,
                            Name = "Deniz`s Vault",
                            UserId = new Guid("c5791f59-1979-4f92-89d4-0bcb203fd9da")
                        });
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.DriversLicense", b =>
                {
                    b.Property<Guid>("Id_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IssuanceDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_key");

                    b.HasIndex("VaultId");

                    b.ToTable("DriversLicenses");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.LocalId", b =>
                {
                    b.Property<Guid>("Id_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Id_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAuthority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_key");

                    b.HasIndex("VaultId");

                    b.ToTable("LocalIds");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.Passport", b =>
                {
                    b.Property<Guid>("Id_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country_of_Issuance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IssuanceDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_key");

                    b.HasIndex("VaultId");

                    b.ToTable("Passports");

                    b.HasData(
                        new
                        {
                            Id_key = new Guid("aa7740bf-00b4-401d-8d76-4c70b84785bb"),
                            Country_of_Issuance = "Turkey",
                            ExpiryDate = new DateTime(2033, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Name = "Deniz`s Passport",
                            IssuanceDate = new DateTime(2023, 11, 17, 23, 11, 56, 231, DateTimeKind.Local).AddTicks(7450),
                            PassportNumber = "U1232232",
                            VaultId = new Guid("c5791f59-1979-4f92-89d4-0bcb203fd9da")
                        });
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.SSN", b =>
                {
                    b.Property<Guid>("Id_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SSNNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_key");

                    b.HasIndex("VaultId");

                    b.ToTable("SSNs");
                });

            modelBuilder.Entity("cis_476_project.Models.CreditCard", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("CreditCards")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.Login", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("LoginCredentials")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.SecurityNote", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("SecurityNotes")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.SecurityQuestion", b =>
                {
                    b.HasOne("cis_476_project.Models.UserAccount", "UserAccount")
                        .WithMany("SecurityQuestions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("cis_476_project.Models.UserAccount", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithOne("UserAccount")
                        .HasForeignKey("cis_476_project.Models.UserAccount", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.DriversLicense", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("DriversLicenses")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.LocalId", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("localIDs")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.Passport", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("Passports")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault_Models.ID.SSN", b =>
                {
                    b.HasOne("cis_476_project.Models.Vault", "Vault")
                        .WithMany("SSNs")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("cis_476_project.Models.UserAccount", b =>
                {
                    b.Navigation("SecurityQuestions");
                });

            modelBuilder.Entity("cis_476_project.Models.Vault", b =>
                {
                    b.Navigation("CreditCards");

                    b.Navigation("DriversLicenses");

                    b.Navigation("LoginCredentials");

                    b.Navigation("Passports");

                    b.Navigation("SSNs");

                    b.Navigation("SecurityNotes");

                    b.Navigation("UserAccount")
                        .IsRequired();

                    b.Navigation("localIDs");
                });
#pragma warning restore 612, 618
        }
    }
}
